version: '3.8'
services:
  spring-boot-app:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - student-network

  react-app:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - student-network

networks:
  student-network:
    driver: bridge