apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: spring-boot-app
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spring-boot-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: spring-boot-app
    spec:
      containers:
        - image: spring-boot-app
          name: spring-boot-app
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
